### ISSUE TITLE
Inner Page Banner: The banner description text should be able to cater to two lines

### ISSUE THREAD

**Issue by bernardtitan** [titan-cebu/Blue-Print#16]
![inner page - 01](https://cloud.githubusercontent.com/assets/11186359/9457349/3185135e-4b14-11e5-9c92-f2fba534a804.jpg)

**Comment by nakul-titan** [comment]
If the content length exceed more than one line then it will cater two lines.

**Comment by maehtitan** [comment]
<b>The width is too wide at the moment compared to the design provided</b>
![image](https://cloud.githubusercontent.com/assets/13363508/9595581/d2071814-509a-11e5-84bf-c916777caf39.png)
