### ISSUE TITLE
Homepage - Banner: The text on the homepage banner should change with every banner transition.

### ISSUE THREAD

**Issue by bernardtitan** [titan-cebu/Blue-Print#20]
The post title should be the banner heading.

The WYSIWYG field content should be the banner description.

The Find out more button should link to the page specified in the banner post Pagelink ACF.

**Comment by nakul-titan** [comment]
I took those fields from Titan options > Global options, after confirming with my TL

**Comment by maehtitan** [comment]
@nakul-titan It's not stated in the scope that the Banner Title, WYSIWYG and button redirection should be implemented under Global Options, it's obviously under Banner section
![image](https://cloud.githubusercontent.com/assets/13363508/9595511/e092eefe-5099-11e5-93a1-af587f6d82e6.png)

**Comment by nakul-titan** [comment]
FYI: There are two kind of banner captions. 1. Static, 2. Movable. For 1st one we cant take from banner section. For 2nd one it should be from banner section. In this project as its a static banner caption my TL suggested me to pull from global options. 
Thanks

**Comment by bernardtitan** [comment]
Hi Nakul,
The usual implementation in Titan goes by the second one, for deviations such as these we need to document it in the scope, as otherwise we'll hold the implementation up to the usual method

**Comment by nakul-titan** [comment]
Hi Bernard,

I spoke to my TL regarding this. He said:
"While creating Project scope doc. I had chat with Bernard on this requirement and Bernard said either ways it works"

**Comment by bernardtitan** [comment]
These kinds of items need to noted on the project scope regardless, as a reference for the people working on the project later on

**Comment by nakul-titan** [comment]
Made project scope updated.
