### ISSUE TITLE
Homepage - Featured Products: The four most recent products are displayed even if they aren't marked as featured, only featured products should be displayed.

### ISSUE THREAD

**Issue by bernardtitan** [titan-cebu/Blue-Print#24]

**Comment by nakul-titan** [comment]
I followed my TL instructions for this. He said display latest 4 products as featured products.

**Comment by maehtitan** [comment]
@nakul-titan The client doesn't have control to the featured products if you have it display by default the latest products uploaded. You can use the featured function column in the product listing.

![image](https://cloud.githubusercontent.com/assets/13363508/9599536/35ed4a98-50c7-11e5-9aaf-e408350e9b05.png)
