### ISSUE TITLE
All Pages: Lists should be displayed in one column

### ISSUE THREAD

**Issue by bernardtitan** [titan-cebu/Blue-Print#27]

**Comment by nakul-titan** [comment]
I have been told by my TL to amend list items to 3 columns in home page welcome content, 2 columns in inner page.

**Comment by maehtitan** [comment]
This was not mentioned in the scope, kindly update it

**Comment by nakul-titan** [comment]
This change was  asked by Fawaaz Cariem
https://projects.titanweb.com.au/public/index.php?path_info=projects/blue-print-pack2/tasks/27
