### ISSUE TITLE
Homepage: Text in lists shouldn't be centered, they should always be left-aligned

### ISSUE THREAD

**Issue by bernardtitan** [titan-cebu/Blue-Print#37]

**Comment by nakul-titan** [comment]
Text in list items is not centered, please show me a screenshot where did you find it is centered.

**Comment by maehtitan** [comment]
Please click the view more text link
![image](https://cloud.githubusercontent.com/assets/13363508/9596822/d9392692-50ac-11e5-9b40-adc079ec8861.png)
