### ISSUE TITLE
Homepage - Ipad: Only 3 featured products shown

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Blue-Print#51]
![image](https://cloud.githubusercontent.com/assets/13363508/9724827/5926bcd0-5610-11e5-922f-284b8d92e424.png)

**Comment by nakul-titan** [comment]
Make sure you have marked required number of products as featured in back end.

**Comment by maehtitan** [comment]
It was really 3 on my part when I was testing yesterday while it was displaying good in landscape view with prev and next button only in portrait the prev and next button disappears
