### ISSUE TITLE
Gallery - Mobile: Center align the images just like how the design implemented, Pls apply fixes also in desktop view coz it so obvious it's not center due to the pagination nav which center-aligned by default

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Blue-Print#53]
<b>Devices: S4, Itouch & Ipad </b>

<b>Portrait views</b>

![image](https://cloud.githubusercontent.com/assets/13363508/9725032/bc3d5dd6-5612-11e5-87dc-c6cb1b92a9f4.png)

<b>Landscape views</b>

![image](https://cloud.githubusercontent.com/assets/13363508/9725064/27f88f8c-5613-11e5-87b1-ae4c745cc554.png)

<b>Desktop view</b>

![image](https://cloud.githubusercontent.com/assets/13363508/9725069/36c12ccc-5613-11e5-981e-b954429744ce.png)

**Comment by nakul-titan** [comment]
Hi  Maeh,

I have aligned single column images perfectly center now. But its not possible to perfectly center multi-column gallery images. Please ignore.

Thanks

**Comment by maehtitan** [comment]
Hello @nakul-titan,

It is possible to make it center perfectly just like the sample here: http://mandurah.stage.titanweb.com.au/our-gallery/ but if you preferred to have it positioned like that in multi-column gallery images .. no worries. thanks
