### ISSUE TITLE
Viewcart: Cart table is cut and it doesn't scroll bottom

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Blue-Print#61]
Devices:
<b>S4 (portrait)</b>
<b>Itouch (portrait)</b>

![image](https://cloud.githubusercontent.com/assets/13363508/9726085/8c21ebfe-5620-11e5-8240-02f9df650eea.png)

**Comment by nakul-titan** [comment]
Its a table layout by Woocommerce. Cant fix.

**Comment by maehtitan** [comment]
It is possible thru CSS, please check the sample site here: http://bollardshop-2015.stage.titanweb.com.au/cart/ table has scroll at the bottom.

So that the table border won't compressed at the edge of the device in S4 portrait
![image](https://cloud.githubusercontent.com/assets/13363508/9750977/aa88d6d2-56d1-11e5-98e1-c4e848967a89.png)

And it won't enabled the sideway scrolling in Itouch which shows the cut layout header and footer
![image](https://cloud.githubusercontent.com/assets/13363508/9751033/2669a5d8-56d2-11e5-8d42-29b9d63667b3.png)

**Comment by nakul-titan** [comment]
Thanks for the reference :)
