### ISSUE TITLE
Product - Listing View: Product is not arrange in ascending order by default regardless of the ordering at the admin area

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Blue-Print#62]
![image](https://cloud.githubusercontent.com/assets/13363508/9726180/232e1918-5622-11e5-953a-4c47bd9b0eaf.png)

**Comment by nakul-titan** [comment]
Admin can select the Product sorting by going to Woocommerce>Settings>Products>Display : Default Product Sorting.

Have a look at the screenshot.
![product-sorting-screen](https://cloud.githubusercontent.com/assets/13461911/9733995/5dfe22ec-564d-11e5-8694-e89bccb62740.jpg)

**Comment by maehtitan** [comment]
It's not the client's/user to set that part, its by default should be alphabetically/numerically ordered

**Comment by nakul-titan** [comment]
As per the KB Article https://knowledgebase.titanweb.com.au/implementation-practices/woocommerce/custom-posts, all custom posts should follow Order attribute, which will give the control on order to the client, but not by alphabetically/numerically. As of now products order is following the same. You can test it by editing any of the products and go to Product Data > Advanced : Menu Order.

**Comment by maehtitan** [comment]
It's not a custom post and it has been a practice since to order it alphabetically in products. Anyway thanks for the fixed, that's the exact order I wanted to achieve. :)
